### Приветствие
GET http://localhost:8080/calculator

### Метод прибалвения
GET http://localhost:8080/calculator/plus?num1=5&num2=5

### Метод вычитания
GET http://localhost:8080/calculator/minus?num1=5&num2=5

### Метод умножения
GET http://localhost:8080/calculator/multiply?num1=5&num2=5

### Метод деления
GET http://localhost:8080/calculator/divide?num1=5&num2=5

